tap "clementtsang/bottom"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "coreutils"
brew "asdf"
brew "bat"
brew "python@3.9"
brew "glib"
brew "unbound"
brew "cask"
brew "llvm"
brew "ccls"
brew "cmake"
brew "gobject-introspection"
brew "harfbuzz"
brew "libass"
brew "srt"
brew "ffmpeg"
brew "figlet"
brew "fzf"
brew "gdb"
brew "git", link: false
brew "gnupg"
brew "htop"
brew "hugo"
brew "lsd"
brew "mas"
brew "neovim"
brew "pfetch"
brew "pyenv"
brew "python@3.8"
brew "ranger"
brew "ruby"
brew "speedtest-cli"
brew "starship"
brew "stow"
brew "tldr"
brew "tmux"
brew "wget"
brew "youtube-dl"
brew "z"
brew "clementtsang/bottom/bottom"

cask "airbuddy"
cask "alfred"
cask "altserver"
cask "amethyst"
cask "brave-browser"
cask "font-jetbrains-mono-nerd-font"
cask "karabiner-elements"
cask "kitty"
cask "lulu"
cask "openemu"
cask "the-unarchiver"
cask "tunnelblick"
cask "virtualbox"

mas "Bear", id: 1091189122
mas "Cleaner One Lite", id: 1473079126
mas "Keynote", id: 409183694
mas "Scenecuts Helper", id: 1540491573
mas "Spark", id: 1176895641
mas "辞書 by 物書堂", id: 1380563956
