tap "clementtsang/bottom"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "louisbrunner/valgrind"
tap "universal-ctags/universal-ctags"
brew "coreutils"
brew "asdf"
brew "bat"
brew "python@3.9"
brew "glib"
brew "unbound"
brew "cask"
brew "llvm"
brew "ccls"
brew "cmake"
brew "gobject-introspection"
brew "harfbuzz"
brew "libass"
brew "srt"
brew "ffmpeg"
brew "figlet"
brew "gdb"
brew "git", link: false
brew "gnupg"
brew "htop"
brew "hugo"
brew "imagemagick"
brew "lsd"
brew "mas"
brew "neovim"
brew "pfetch"
brew "pyenv"
brew "python@3.8"
brew "ranger"
brew "ruby"
brew "speedtest-cli"
brew "starship"
brew "stow"
brew "tldr"
brew "tmux"
brew "vim"
brew "wget"
brew "youtube-dl"
brew "z"
brew "clementtsang/bottom/bottom"
cask "airbuddy"
cask "alfred"
cask "amethyst"
cask "brave-browser"
cask "discord"
cask "font-jetbrains-mono-nerd-font"
cask "karabiner-elements"
cask "kitty"
cask "lulu"
cask "notion"
cask "obsidian"
cask "the-unarchiver"
cask "tomighty"
cask "tunnelblick"
cask "virtualbox"
cask "visual-studio-code"
cask "zoom"
mas "Bear", id: 1091189122
mas "Drafts", id: 1435957248
mas "Kindle", id: 405399194
mas "LINE", id: 539883307
mas "Scenecuts Helper", id: 1540491573
mas "Thor Launcher", id: 1120999687
mas "Unsplash Wallpapers", id: 1284863847
mas "辞書 by 物書堂", id: 1380563956
