[line_break]
disabled = true
[cmd_duration]
disabled = true
[git_status]
disabled = true
[username]
style_user = "#45ba45"
style_root = "bold yellow"
format = "[$user]($style) in "
disabled = true 
show_always = true
[directory]
style = "#00e786"
[git_branch]
style = "#e16e6a"
[character]
success_symbol = "[❯](bold white)"
error_symbol = "[❯](bold red)"
