#      _                 _     _             _                  _
#  ___| |_ __ _ _ __ ___| |__ (_)_ __       | |_ ___  _ __ ___ | |
# / __| __/ _` | '__/ __| '_ \| | '_ \      | __/ _ \| '_ ` _ \| |
# \__ \ || (_| | |  \__ \ | | | | |_) |  _  | || (_) | | | | | | |
# |___/\__\__,_|_|  |___/_| |_|_| .__/  (_)  \__\___/|_| |_| |_|_|
#                               |_|

add_newline = false
[line_break]
disabled = true
[cmd_duration]
disabled = true
[git_status]
disabled = true
[username]
style_user = "#45ba45"
style_root = "bold yellow"
format = "[$user]($style) in "
disabled = true 
show_always = true
[directory]
style = "#8be200"
[git_branch]
style = "#e7005c"
[character]
success_symbol = "[❯](bold white)"
error_symbol = "[❯](bold red)"
