#      _                 _     _             _                  _
#  ___| |_ __ _ _ __ ___| |__ (_)_ __       | |_ ___  _ __ ___ | |
# / __| __/ _` | '__/ __| '_ \| | '_ \      | __/ _ \| '_ ` _ \| |
# \__ \ || (_| | |  \__ \ | | | | |_) |  _  | || (_) | | | | | | |
# |___/\__\__,_|_|  |___/_| |_|_| .__/  (_)  \__\___/|_| |_| |_|_|
#                               |_|

add_newline = false

format = """
[╭── ](bold white)$all\
[╰─](bold white)$character"""

scan_timeout = 10

[line_break]
disabled = false

[cmd_duration]
style = "italic yellow"
format = "took [ $duration]($style)"
disabled = false

[battery]
	disabled = true

[username]
style_user = "italic cyan"
format = "[ riceset]($style) at "
# style_root = "italic"
show_always = true

[package]
style = "italic 208"
symbol = " "

[character]
success_symbol = "[❯](bold white)"
error_symbol = "[❯](bold #red)"

[aws]
symbol = "  "

[buf]
symbol = " "
format = "via [$symbol]($style)"

[c]
symbol = " "
format = "via [$symbol]($style)"

[conda]
symbol = " "

[dart]
symbol = " "
format = "via [$symbol]($style)"

[directory]
style = "italic green"
read_only = "  "
home_symbol = " "
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = true
repo_root_format = "[$read_only]($read_only_style)($style)[$repo_root]($style)[$path]($style) "
repo_root_style = ""

[docker_context]
style = "italic blue"
symbol = " "

[elixir]
symbol = " "
format = "via [$symbol]($style)"

[elm]
symbol = " "
format = "via [$symbol]($style)"

[git_branch]
symbol = " "
style = "italic red"

[git_status]
style = "bold yellow"
ahead = "▲ ${count}"
behind = "▼ ${count}"
diverged = "▲ ${ahead_count} ▼ ${behind_count}"

[golang]
symbol = " "
format = "via [$symbol]($style)"

[haskell]
symbol = " "
format = "via [$symbol]($style)"

[hg_branch]
symbol = " "

[java]
symbol = " "
format = "via [$symbol]($style)"

[julia]
symbol = " "
format = "via [$symbol]($style)"

[nim]
symbol = " "
format = "via [$symbol]($style)"

[nix_shell]
symbol = " "
format = "via [$symbol]($style)"

[nodejs]
symbol = " "
format = "via [$symbol]($style)"

[python]
symbol = " "
format = "via [$symbol]($style)"

[spack]
symbol = "🅢 "
format = "via [$symbol]($style)"

[rust]
symbol = " "
format = "via [$symbol]($style)"

[lua]
symbol = " "
format = 'via [$symbol]($style)'

[ruby]
symbol = " "
format = 'via [$symbol]($style)'
