add_newline = false

format = """
[╭── ](bold)$all\
[╰─](bold)$character"""

scan_timeout = 10

[line_break]
disabled = false

[cmd_duration]
style = "italic yellow"
format = "took [ $duration]($style)"
disabled = true

[battery]
	disabled = true

[username]
style_user = "italic yellow"
format = "[riceset]($style) at "
# style_root = "italic"
show_always = true

[package]
style = "italic 208"
symbol = " "
disabled = true

[character]
success_symbol = "[❯](bold)"
error_symbol = "[❯](bold #red)"

[aws]
symbol = "  "
disabled = true

[buf]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[c]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[conda]
symbol = " "
disabled = true

[dart]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[directory]
style = "italic green"
read_only = "  "
# home_symbol = " "
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = true
repo_root_format = "[$read_only]($read_only_style)($style)[$repo_root]($style)[$path]($style) "
repo_root_style = ""
truncation_length = 3
use_logical_path = false

[docker_context]
style = "italic blue"
symbol = " "

[elixir]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[elm]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[git_branch]
symbol = " "
style = "italic red"

[git_status]
style = "bold red"
ahead = "▲ ${count}"
behind = "▼ ${count}"
diverged = "▲ ${ahead_count} ▼ ${behind_count}"

[golang]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[haskell]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[hg_branch]
symbol = " "

[java]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[julia]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[nim]
symbol = " "
disabled = true
format = "via [$symbol]($style)"

[nix_shell]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[nodejs]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[python]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[spack]
symbol = "🅢 "
format = "via [$symbol]($style)"
disabled = true

[rust]
symbol = " "
format = "via [$symbol]($style)"
disabled = true

[lua]
symbol = " "
format = 'via [$symbol]($style)'
disabled = true

[ruby]
symbol = " "
format = 'via [$symbol]($style)'
disabled = true

[swift]
disabled = true
