#      _                 _     _             _                  _
#  ___| |_ __ _ _ __ ___| |__ (_)_ __       | |_ ___  _ __ ___ | |
# / __| __/ _` | '__/ __| '_ \| | '_ \      | __/ _ \| '_ ` _ \| |
# \__ \ || (_| | |  \__ \ | | | | |_) |  _  | || (_) | | | | | | |
# |___/\__\__,_|_|  |___/_| |_|_| .__/  (_)  \__\___/|_| |_| |_|_|
#                               |_|

add_newline = false
command_timeout = 999

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "#DFDD51"

[line_break]
disabled = true

[cmd_duration]
disabled = false

[username]
style_user = "#81CE6B"
style_root = "bold #DFDD51"
format = "[$user]($style) in "
disabled = true
show_always = true

[package]
symbol = " "

[character]
success_symbol = "[❯](bold #ffffff)"
error_symbol = "[❯](bold #F8586E)"

[aws]
symbol = "  "

[buf]
symbol = " "
format = "via [$symbol]($style)"

[c]
symbol = " "
format = "via [$symbol]($style)"

[conda]
symbol = " "

[dart]
symbol = " "
format = "via [$symbol]($style)"

[directory]
style = "#81CE6B"
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "
format = "via [$symbol]($style)"

[elm]
symbol = " "
format = "via [$symbol]($style)"

[git_branch]
symbol = " "
style = "#F8586E"

[golang]
symbol = " "
format = "via [$symbol]($style)"

[haskell]
symbol = " "
format = "via [$symbol]($style)"

[hg_branch]
symbol = " "

[java]
symbol = " "
format = "via [$symbol]($style)"

[julia]
symbol = " "
format = "via [$symbol]($style)"

[memory_usage]
symbol = " "

[nim]
symbol = " "
format = "via [$symbol]($style)"

[nix_shell]
symbol = " "
format = "via [$symbol]($style)"

[nodejs]
symbol = " "
format = "via [$symbol]($style)"

[python]
symbol = " "
format = "via [$symbol]($style)"

[spack]
symbol = "🅢 "
format = "via [$symbol]($style)"

[rust]
symbol = " "
format = "via [$symbol]($style)"

[lua]
symbol = " "
format = 'via [$symbol]($style)'

[ruby]
symbol = " "
format = 'via [$symbol]($style)'
